// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_CharacterChoices","status":true,"description":"Allows the use of the \"Show Choices\" event to have the Player to select an animated Character.","parameters":{"Walking Speed":"15","Character Padding":"18","Sprite Width":"48","Sprite Height":"48","X Offset":"12","Y Offset":"14"}},
{"name":"SRD_SuperToolsEngine","status":true,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"true","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_RemoveTitleScreen","status":true,"description":"This Plugin removes the title screen from the game.","parameters":{}},
{"name":"SRD_HUDMaker","status":true,"description":"Allows developers to create their own map-based HUD through an in-game GUI window!","parameters":{"Active Updating":"false","Show During Events":"transparent","Map Global Condition":"","Battle Global Condition":"","Disable Delete Key":"true"}},
{"name":"SRD_BitmapUpgrade","status":true,"description":"Adds various Bitmap functions to allow color transformations to characters, battlers, and weapons.","parameters":{"Default Font":"GameFont","Default Font Size":"28","Default Font Italic":"false","Default Text Color":"#FFFFFF","Default Outline Color":"rgba(0, 0, 0, 0.5)","Default Outline Width":"4"}},
{"name":"SRD_CopyActors","status":true,"description":"Allows you to copy Actors to have multiple instances of the same Actor in your game.","parameters":{"Initial Copy Mode":"true","Starting Copy ID":"1001"}}
];
